INSERT INTO TIPO (id, nome) VALUES (1, 'ATENDENTE');
INSERT INTO TIPO (id, nome) VALUES (2, 'GERENTE DE OFICINA');
INSERT INTO TIPO (id, nome) VALUES (3, 'FUNILEIRO');
INSERT INTO TIPO (id, nome) VALUES (4, 'FINANCEIRO');
INSERT INTO TIPO (id, nome) VALUES (5, 'CLIENTE');


INSERT INTO ROLE (id, nome) VALUES (1, 'ADMIN');
INSERT INTO ROLE (id, nome) VALUES (2, 'ADMINISTRATIVO');
INSERT INTO ROLE (id, nome) VALUES (3, 'USUÁRIO');